RMB-874: Update Vert.x to 4.1.4 and okapi-common to 4.9.0
Running a module with RMB 33.1.0 and Vert.x >= 4.1.3 causes this failure at runtime:

java.lang.NoSuchMethodError: 'java.lang.Object io.vertx.core.Context.getLocal(java.lang.String)'
        at org.folio.okapi.common.logging.FolioLoggingContext.lookup(FolioLoggingContext.java:62)

Vert.x <= 4.1.2 uses Context.getLocal(String).
Vert.x >= 4.1.3 uses Context.getLocal(Object).
https://github.com/eclipse-vertx/vert.x/commit/4d408d28d764d1eac65dccefa1578251f0060e5f

okapi-common < 4.9.0 uses Vert.x <= 4.1.2 yielding Context.getLocal(String).
okapi-common >= 4.9.0 uses Vert.x >= 4.1.3 yielding Context.getLocal(Object).
https://github.com/folio-org/okapi/commit/625c85021d0689fdc3872048a4b7249efc5c771b