Update to OpenJDK-11 RMB-328 RMB-682 RMB-690 (#742)
* Create maven.yml

* RMB-682 rewrite guava ClassPath class so that it doesn't depend on other guava classes

* - update postgresql-embedded to fix 'java.lang.NoSuchFieldException: handle' exception in cql2pgjson module

* - add commons-io to resolve 'java.lang.NoClassDefFoundError: org/apache/commons/io/filefilter/TrueFileFilter' in cql2pgjson module

* dbschema and cql2pgson package has own namespace

* RMB-690  update postgresql-embedded to fix 'java.lang.NoSuchFieldException: handle' exception in domain-modules-runtime module
- rollback to 2.22.x version of surefire/failsafe plugins to prevent execution of tests in a modular way

* Update upgrading notes for OpenJDK 11

* Update maven-compiler-plugin version as well

* Fix link for RMB-328

* Trigger OpenJDK 11 build on Jenkins

* Add license for Guava ClassPath

* Fix copyright notices, add ClassPathTest

* Fix implementation bugs reported by unit tests

* Add Java 11 mod-inventory-storage upgrade example

Co-authored-by: Dmytro Tkachenko <dmytro_tkachenko@epam.com>
Co-authored-by: Julian Ladisch <julianladisch@users.noreply.github.com>