Update com.google.guava to 27.1-jre
This makes AnnotationGrabberTest succeed (when enabled).
Now, however GenerateRunnerTest breaks with:

java.lang.NoSuchMethodError: com.google.common.collect.\
  FluentIterable.of([Ljava/lang/Object;)\
  Lcom/google/common/collect/FluentIterable;

The suspect is raml-for-jaxrs 3.0.5 which was created with
com.google.guava 19.0.